# Generated by Django 5.1.1 on 2024-09-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_orcamento_especificacao_orcamento_metros_quadrados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='especificacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
