# Generated by Django 5.1.1 on 2024-09-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_orcamento_especificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='especificacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
