# Generated by Django 5.1.1 on 2024-09-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_fornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='quantidade',
        ),
    ]
