# Generated by Django 5.1.1 on 2024-09-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_orcamento_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='metros_quadrados',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='especificacao',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Pendente', 'Pendente'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('UND', 'UND'), ('M²', 'M²')], default='UND', max_length=20),
        ),
    ]
