# Generated by Django 5.1.1 on 2024-09-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_orcamento_metros_quadrados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='especificacao',
            field=models.CharField(choices=[('UND', 'UND'), ('M²', 'M²')], default='UND', max_length=20),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Pendente', 'Pendente'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=20),
        ),
    ]
